data_path: ontime/data
port_call:
  filename: IHS_PORT_PERFORMANCE.xlsx
  sheet: Sheet1
sales:
  filename: Retail Sales 202210.xlsx
  sheet: Sales
cpi:
  filename: CPI Core 202210.xlsx
  sheet: Core CPI
air_freight:
  filename: AirFrieght total Rate USD per 1000kg Shanghai to Los angeles.xlsx
  sheet": Sheet1
