# data path
data_path: ontime/data

# schedule
schedule:
  filename: 2022-11-29TableMapping_Reliability-SCHEDULE_RELIABILITY_PP.csv

# port call
port_call:
  filename: IHS_PORT_PERFORMANCE.xlsx
  sheet: Sheet1

# retail sales
sales:
  filename: Retail Sales 202210.xlsx
  sheet: Sales

# consumer price index
cpi:
  filename: CPI Core 202210.xlsx
  sheet: Core CPI

# air freight
air_freight:
  filename: AirFrieght total Rate USD per 1000kg Shanghai to Los angeles.xlsx
  sheet: Sheet1

# freight

# evaluation
eval:
  split_month: 8
  max_month: 9
  label: "Avg_TTDays"
  partial_pred: False
  overall_pred: True
  eval_lin_reg: False
  include_reg: True

  restrict_trade: True

  trade_option: "Asia-North America West Coast"
  carrier_option: "ANL"
  service_option: "EPIC"

